/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.umg.callcenter.atencion.normal.ui;

/**
 *
 * @author mk
 */

import com.umg.callcenter.atencion.normal.controller.AtencionController;
import com.umg.callcenter.atencion.normal.modelo.Cliente;
import com.google.gson.JsonObject;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;

public class ui extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ui.class.getName());

    /**
     * Creates new form NewJFrame
     */
    
    private AtencionController controller;
    private String tipoAgente;     // "normal" o "premium"
    private String nombreAgente;
    private DefaultTableModel modeloTablaEspera;
    private Timer progressTimer;

    // Para el chat
    private JFrame ventanaChat;
    private JTextArea txtAreaChat;
    private JTextField txtMensajeChat;
    private DefaultListModel<String> modeloUsuarios;
    private Timer actualizarUsuariosTimer;
    
    public ui() {
        this.tipoAgente = "normal";
        this.nombreAgente = "Agente";
        initComponents();
        inicializarPersonalizado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_ip = new javax.swing.JTextField();
        btn_apply_IP = new javax.swing.JButton();
        btn_preset_IP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        server_Status = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        normal_counter = new javax.swing.JLabel();
        premium_counter = new javax.swing.JLabel();
        agent_txt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneActual = new javax.swing.JTextPane();
        titulo1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        titulo2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        titulo3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPaneActual1 = new javax.swing.JTextPane();
        txt_motive = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_duration = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_finalizarAtencion = new javax.swing.JButton();
        btn_chat = new javax.swing.JButton();
        btn_takeNextCliente = new javax.swing.JButton();
        titulo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        titulo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(101, 102, 246));
        titulo.setText("Atencion General");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("IP Servidor:");

        txt_ip.setBackground(new java.awt.Color(245, 245, 245));
        txt_ip.setForeground(new java.awt.Color(102, 102, 255));

        btn_apply_IP.setBackground(new java.awt.Color(234, 234, 234));
        btn_apply_IP.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        btn_apply_IP.setForeground(new java.awt.Color(102, 102, 255));
        btn_apply_IP.setText("Aplicar IP");

        btn_preset_IP.setBackground(new java.awt.Color(234, 234, 234));
        btn_preset_IP.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        btn_preset_IP.setForeground(new java.awt.Color(102, 102, 255));
        btn_preset_IP.setText("IP Predefinida");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Agente:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cola Premium:");

        server_Status.setBackground(new java.awt.Color(255, 255, 255));
        server_Status.setForeground(new java.awt.Color(0, 0, 0));
        server_Status.setText("Status del servidor");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cola Normal:");

        normal_counter.setBackground(new java.awt.Color(255, 255, 255));
        normal_counter.setForeground(new java.awt.Color(0, 0, 0));
        normal_counter.setText("0");

        premium_counter.setBackground(new java.awt.Color(255, 255, 255));
        premium_counter.setForeground(new java.awt.Color(0, 0, 0));
        premium_counter.setText("0");

        agent_txt.setBackground(new java.awt.Color(255, 255, 255));
        agent_txt.setForeground(new java.awt.Color(0, 0, 0));
        agent_txt.setText("--");

        jTextPaneActual.setBackground(new java.awt.Color(245, 245, 245));
        jTextPaneActual.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jTextPaneActual);

        titulo1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        titulo1.setForeground(new java.awt.Color(101, 102, 246));
        titulo1.setText("Cliente Actual");

        jTable1.setBackground(new java.awt.Color(245, 245, 245));
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        titulo2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        titulo2.setForeground(new java.awt.Color(101, 102, 246));
        titulo2.setText("Clientes en Espera (NORMAL)");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Motivo:");

        titulo3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        titulo3.setForeground(new java.awt.Color(101, 102, 246));
        titulo3.setText("Clientes en Espera (NORMAL)");

        jTextPaneActual1.setBackground(new java.awt.Color(245, 245, 245));
        jTextPaneActual1.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane3.setViewportView(jTextPaneActual1);

        txt_motive.setBackground(new java.awt.Color(245, 245, 245));
        txt_motive.setForeground(new java.awt.Color(102, 102, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Duracion (min):");

        txt_duration.setBackground(new java.awt.Color(245, 245, 245));
        txt_duration.setForeground(new java.awt.Color(102, 102, 255));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("1 - 480");

        btn_finalizarAtencion.setBackground(new java.awt.Color(234, 234, 234));
        btn_finalizarAtencion.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        btn_finalizarAtencion.setForeground(new java.awt.Color(102, 102, 255));
        btn_finalizarAtencion.setText("Finalizar Atencion");

        btn_chat.setBackground(new java.awt.Color(234, 234, 234));
        btn_chat.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        btn_chat.setForeground(new java.awt.Color(102, 102, 255));
        btn_chat.setText("Chat");

        btn_takeNextCliente.setBackground(new java.awt.Color(102, 102, 255));
        btn_takeNextCliente.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        btn_takeNextCliente.setForeground(new java.awt.Color(234, 234, 234));
        btn_takeNextCliente.setText("Tomar siguiente cliente");

        titulo4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        titulo4.setForeground(new java.awt.Color(101, 102, 246));
        titulo4.setText("Registro de Actividades:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(premium_counter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(agent_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_ip)
                                .addGap(44, 44, 44)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(normal_counter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btn_apply_IP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(server_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_preset_IP, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo2)
                            .addComponent(titulo1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_chat)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_duration, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_motive)))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_finalizarAtencion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_takeNextCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titulo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_chat, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_apply_IP)
                    .addComponent(btn_preset_IP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(agent_txt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(premium_counter)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(normal_counter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(server_Status)))
                .addGap(26, 26, 26)
                .addComponent(titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titulo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_motive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_takeNextCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btn_finalizarAtencion))
                .addGap(26, 26, 26)
                .addComponent(titulo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // ========== CONSTRUCTOR MODIFICADO ==========
    public ui(String tipoAgente, String nombreAgente) {
        this.tipoAgente = tipoAgente.toLowerCase();
        this.nombreAgente = nombreAgente;
        initComponents();
        inicializarPersonalizado();
    }


    // ========== INICIALIZACIÓN ==========
    private void inicializarPersonalizado() {
        // 1. Crear el controller
        this.controller = new AtencionController(tipoAgente, nombreAgente);

        // 2. Configurar la tabla de clientes en espera
        String[] columnas = {"Ticket", "DPI", "Nombre", "Hora Ingreso"};
        modeloTablaEspera = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(modeloTablaEspera);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // 3. Configurar título según el tipo
        if (tipoAgente.equals("premium")) {
            titulo.setText("⭐ ATENCIÓN PREMIUM");
            titulo.setForeground(new Color(255, 153, 102));
            btn_takeNextCliente.setBackground(new Color(255, 153, 102));
            titulo2.setText("Clientes en Espera (PREMIUM)");
        } else {
            titulo.setText("📞 ATENCIÓN GENERAL");
            titulo.setForeground(new Color(102, 102, 255));
            btn_takeNextCliente.setBackground(new Color(102, 102, 255));
            titulo2.setText("Clientes en Espera (NORMAL)");
        }

        // 4. Configurar áreas de texto
        jTextPaneActual.setEditable(false);
        jTextPaneActual1.setEditable(false);
        jTextPaneActual1.setFont(new Font("Monospaced", Font.PLAIN, 11));

        // 5. Configurar campos de formulario (inicialmente deshabilitados)
        txt_motive.setEnabled(false);
        txt_duration.setEnabled(false);
        btn_finalizarAtencion.setEnabled(false);

        // 6. Configurar texto del agente
        agent_txt.setText(nombreAgente);

        // 7. Configurar IP por defecto
        txt_ip.setText(controller.getHostActual());

        // 8. Configurar eventos
        configurarEventos();

        // 9. Configurar callbacks del controller
        configurarCallbacks();

        // 10. Conectar al servidor
        controller.conectar();
    }

    private void configurarEventos() {
        // Botón Aplicar IP
        btn_apply_IP.addActionListener(e -> {
            String nuevaIp = txt_ip.getText().trim();
            if (!nuevaIp.isEmpty()) {
                controller.cambiarIpServidor(nuevaIp);
            }
        });

        // Botón IP Predefinida
        btn_preset_IP.addActionListener(e -> {
            String ipPredefinida = "25.4.40.151"; // Cambia según tu configuración
            txt_ip.setText(ipPredefinida);
            controller.cambiarIpServidor(ipPredefinida);
            agregarLog("🔧 Usando IP predefinida: " + ipPredefinida);
        });

        // Botón Tomar Siguiente Cliente
        btn_takeNextCliente.addActionListener(e -> controller.tomarSiguienteCliente());

        // Botón Finalizar Atención
        btn_finalizarAtencion.addActionListener(this::finalizarAtencion);

        // Botón Chat
        btn_chat.addActionListener(e -> abrirChat());

        // Doble click en tabla para tomar cliente específico
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int row = jTable1.getSelectedRow();
                    if (row >= 0) {
                        if (controller.getClienteActual() != null) {
                            JOptionPane.showMessageDialog(null,
                                    "Ya tienes un cliente en atención. Finalízalo primero.",
                                    "Cliente activo",
                                    JOptionPane.WARNING_MESSAGE);
                            return;
                        }

                        String ticket = modeloTablaEspera.getValueAt(row, 0).toString();
                        String nombre = modeloTablaEspera.getValueAt(row, 2).toString();
                        String hora = modeloTablaEspera.getValueAt(row, 3).toString();

                        int confirm = JOptionPane.showConfirmDialog(
                                null,
                                "¿Tomar este cliente?\n\nTicket: " + ticket + "\nCliente: " + nombre + "\nIngreso: " + hora,
                                "Confirmar atención",
                                JOptionPane.YES_NO_OPTION,
                                JOptionPane.QUESTION_MESSAGE
                        );

                        if (confirm == JOptionPane.YES_OPTION) {
                            controller.tomarClienteSeleccionado(ticket);
                        }
                    }
                }
            }
        });
    }

    private void configurarCallbacks() {
        controller.setOnConectar(() -> {
            server_Status.setText("🟢 Conectado al Servidor");
            server_Status.setForeground(new Color(0, 150, 0));
            btn_takeNextCliente.setEnabled(true);
            txt_ip.setText(controller.getHostActual());
        });

        controller.setOnErrorConexion(() -> {
            server_Status.setText("🔴 Sin conexión");
            server_Status.setForeground(Color.RED);
            btn_takeNextCliente.setEnabled(false);
        });
        
        controller.setOnAtencionRegistrada(() -> {
            SwingUtilities.invokeLater(() -> {
                txt_motive.setText("");
                txt_duration.setText("");
                habilitarRegistroAtencion(false);
                agregarLog("✅ Atención registrada exitosamente");
                controller.actualizarListaClientes();
                btn_takeNextCliente.setEnabled(true);
            });
        });
        controller.setOnLog(this::agregarLog);

        controller.setOnActualizarContadores((normal, premium) -> {
            normal_counter.setText(String.valueOf(normal));
            premium_counter.setText(String.valueOf(premium));
        });

        controller.setOnClienteAsignado(respuestaJson -> {
            String ticket = respuestaJson.get("ticket").getAsString();
            String dpi = respuestaJson.get("dpi").getAsString();
            String nombre = respuestaJson.get("nombre").getAsString();
            String apellido = respuestaJson.get("apellido").getAsString();
            String tipo = respuestaJson.get("tipo").getAsString();

            Cliente nuevoCliente = new Cliente(ticket, dpi, nombre, apellido, tipo);
            mostrarClienteEnUI(nuevoCliente);
            controller.setClienteActual(nuevoCliente);
            habilitarRegistroAtencion(true);
            agregarLog("📞 Cliente asignado: " + ticket + " - " + nombre + " " + apellido);
            controller.actualizarListaClientes();
        });

        controller.setOnError(errorMsg -> agregarLog("❌ Error: " + errorMsg));

        controller.setOnClienteFinalizado(() -> {
            jTextPaneActual.setText("✅ Atención finalizada\n\nPresione 'Tomar Siguiente Cliente' para continuar.");
            txt_motive.setText("");
            txt_duration.setText("");
            habilitarRegistroAtencion(false);
            controller.setClienteActual(null);
        });

        controller.setOnActualizarTabla(this::actualizarTablaClientes);

        // Callbacks para chat
        controller.setOnMensajeChat(mensaje -> {
            SwingUtilities.invokeLater(() -> {
                if (txtAreaChat != null) {
                    txtAreaChat.append(mensaje + "\n");
                    txtAreaChat.setCaretPosition(txtAreaChat.getDocument().getLength());
                }
            });
        });

        controller.setOnActualizarUsuariosChat(usuarios -> {
            SwingUtilities.invokeLater(() -> {
                if (modeloUsuarios != null) {
                    modeloUsuarios.clear();
                    for (var u : usuarios) {
                        modeloUsuarios.addElement(u.getAsString());
                    }
                }
            });
        });
    }

    private void mostrarClienteEnUI(Cliente cliente) {
        StringBuilder sb = new StringBuilder();
        sb.append("╔══════════════════════════════════════════════════╗\n");
        sb.append("║              DATOS DEL CLIENTE                   ║\n");
        sb.append("╠══════════════════════════════════════════════════╣\n");
        sb.append(String.format("║ Ticket: %-36s ║\n", cliente.getTicket()));
        sb.append(String.format("║ DPI:    %-36s ║\n", cliente.getDpi()));
        sb.append(String.format("║ Nombre: %-36s ║\n", cliente.getNombreCompleto()));
        sb.append(String.format("║ Tipo:   %-36s ║\n", cliente.getTipo().toUpperCase()));
        sb.append("╚══════════════════════════════════════════════════╝");
        jTextPaneActual.setText(sb.toString());
    }

    private void actualizarTablaClientes(java.util.List<JsonObject> clientes) {
        modeloTablaEspera.setRowCount(0);
        for (JsonObject obj : clientes) {
            modeloTablaEspera.addRow(new Object[]{
                obj.get("ticket").getAsString(),
                obj.get("dpi").getAsString(),
                obj.get("nombre").getAsString(),
                obj.get("hora").getAsString()
            });
        }
    }

    private void finalizarAtencion(ActionEvent evt) {
        String motivo = txt_motive.getText().trim();
        String duracionStr = txt_duration.getText().trim();

        if (motivo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el motivo de la atención");
            return;
        }

        int duracion;
        try {
            duracion = Integer.parseInt(duracionStr);
            if (duracion < 1 || duracion > 480) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese una duración válida (1-480 minutos)");
            return;
        }

        Cliente clienteActual = controller.getClienteActual();
        if (clienteActual == null) {
            agregarLog("❌ No hay cliente actual para finalizar");
            return;
        }

        // Confirmar finalización
        int confirm = JOptionPane.showConfirmDialog(
                null,
                "¿Finalizar atención?\n\nTicket: " + clienteActual.getTicket() + "\nCliente: " + clienteActual.getNombreCompleto()
                + "\n\nMotivo: " + motivo + "\nDuración: " + duracion + " minutos",
                "Confirmar finalización",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        btn_finalizarAtencion.setEnabled(false);
        btn_takeNextCliente.setEnabled(false);

        controller.finalizarAtencion(motivo, duracion);
        agregarLog("⏳ Finalizando atención...");
    }

    private void habilitarRegistroAtencion(boolean habilitado) {
        txt_motive.setEnabled(habilitado);
        txt_duration.setEnabled(habilitado);
        btn_finalizarAtencion.setEnabled(habilitado);
        if (habilitado) {
            txt_motive.requestFocus();
        }
    }

    private void agregarLog(String mensaje) {
        SwingUtilities.invokeLater(() -> {
            String timestamp = java.time.LocalDateTime.now()
                    .format(java.time.format.DateTimeFormatter.ofPattern("HH:mm:ss"));
            String linea = "[" + timestamp + "] " + mensaje + "\n";

            // Usar jTextPaneActual1 como área de log (Actividades)
            String actual = jTextPaneActual1.getText();
            jTextPaneActual1.setText(actual + linea);

            // Auto-scroll al final
            jTextPaneActual1.setCaretPosition(jTextPaneActual1.getDocument().getLength());

            // Limitar líneas (opcional)
            if (jTextPaneActual1.getText().split("\n").length > 200) {
                String[] lineas = jTextPaneActual1.getText().split("\n");
                StringBuilder sb = new StringBuilder();
                for (int i = lineas.length - 150; i < lineas.length; i++) {
                    if (i >= 0) {
                        sb.append(lineas[i]).append("\n");
                    }
                }
                jTextPaneActual1.setText(sb.toString());
            }
        });
    }

    // ========== MÉTODOS DE CHAT ==========
    private void abrirChat() {
        if (ventanaChat == null || !ventanaChat.isVisible()) {
            crearVentanaChat();
        }
        ventanaChat.setVisible(true);
        ventanaChat.toFront();

        Timer timer = new Timer(500, e -> controller.solicitarUsuariosChat());
        timer.setRepeats(false);
        timer.start();
    }

    private void crearVentanaChat() {
        ventanaChat = new JFrame("Chat - Call Center UMG");
        ventanaChat.setSize(500, 600);
        ventanaChat.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        ventanaChat.setLocationRelativeTo(this);

        JPanel panel = new JPanel(new BorderLayout(5, 5));
        panel.setBorder(new EmptyBorder(10, 10, 10, 10));

        modeloUsuarios = new DefaultListModel<>();
        JList<String> listaUsuarios = new JList<>(modeloUsuarios);
        listaUsuarios.setPreferredSize(new Dimension(150, 0));
        JScrollPane scrollUsuarios = new JScrollPane(listaUsuarios);
        scrollUsuarios.setBorder(BorderFactory.createTitledBorder("Usuarios Conectados"));

        txtAreaChat = new JTextArea();
        txtAreaChat.setEditable(false);
        txtAreaChat.setFont(new Font("Monospaced", Font.PLAIN, 12));
        JScrollPane scrollChat = new JScrollPane(txtAreaChat);
        scrollChat.setBorder(BorderFactory.createTitledBorder("Mensajes"));

        JPanel panelEnvio = new JPanel(new BorderLayout(5, 5));
        txtMensajeChat = new JTextField();
        txtMensajeChat.addActionListener(e -> enviarMensajeChat());
        JButton btnEnviar = new JButton("Enviar");
        btnEnviar.addActionListener(e -> enviarMensajeChat());
        panelEnvio.add(txtMensajeChat, BorderLayout.CENTER);
        panelEnvio.add(btnEnviar, BorderLayout.EAST);

        panel.add(scrollChat, BorderLayout.CENTER);
        panel.add(scrollUsuarios, BorderLayout.EAST);
        panel.add(panelEnvio, BorderLayout.SOUTH);

        ventanaChat.add(panel);

        actualizarUsuariosTimer = new Timer(5000, e -> controller.solicitarUsuariosChat());
        actualizarUsuariosTimer.start();

        ventanaChat.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (actualizarUsuariosTimer != null) {
                    actualizarUsuariosTimer.stop();
                }
            }
        });
    }

    private void enviarMensajeChat() {
        String mensaje = txtMensajeChat.getText().trim();
        if (mensaje.isEmpty()) {
            return;
        }
        controller.enviarMensajeChat(mensaje);
        txtMensajeChat.setText("");
    }

    @Override
    public void dispose() {
        if (controller != null) {
            controller.desconectar();
        }
        super.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ui().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agent_txt;
    private javax.swing.JButton btn_apply_IP;
    private javax.swing.JButton btn_chat;
    private javax.swing.JButton btn_finalizarAtencion;
    private javax.swing.JButton btn_preset_IP;
    private javax.swing.JButton btn_takeNextCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPaneActual;
    private javax.swing.JTextPane jTextPaneActual1;
    private javax.swing.JLabel normal_counter;
    private javax.swing.JLabel premium_counter;
    private javax.swing.JLabel server_Status;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo4;
    private javax.swing.JTextField txt_duration;
    private javax.swing.JTextField txt_ip;
    private javax.swing.JTextField txt_motive;
    // End of variables declaration//GEN-END:variables
}
